"""Shared schemas for Campus Job Agent."""

from campus_job_agent.schemas.candidate import (
    CandidateProfile,
    CapabilityAssessment,
    EducationRecord,
    EvidenceCoverage,
    ExperienceRecord,
    ResponsibilityBoundary,
)
from campus_job_agent.schemas.candidate_graph import (
    BudgetState,
    CandidateProfileGraphState,
    CounterState,
    InformationGap,
    ProfileCorrection,
    ProfileVersionDiff,
    QuestionItem,
    QuestionPlan,
    SufficiencyAssessment,
)
from campus_job_agent.schemas.document import DocumentExtraction, ExtractionUnit
from campus_job_agent.schemas.evidence import (
    ClaimExtractionBatch,
    ClaimExtractor,
    EvidenceArtifact,
    EvidenceClaim,
    EvidenceFragment,
    ExtractedClaim,
    ProfileSnapshot,
    Provenance,
)
from campus_job_agent.schemas.gap import GapAssessment, GapItem, migrate_legacy_gap_assessment
from campus_job_agent.schemas.goal import ParsedGoal, PlanTask, SearchGoal
from campus_job_agent.schemas.intent import CareerIntent, IntentConstraint, migrate_legacy_career_intent
from campus_job_agent.schemas.matching import (
    ComparisonEntry,
    ComparisonSet,
    CoverageBreakdown,
    CoverageContribution,
    JobMatchExplanation,
    MatchExplanation,
    MatchingInputSet,
    PreferenceAssessment,
    QualificationAssessment,
    RequirementAssessment,
)
from campus_job_agent.schemas.decision import (
    ComparisonReviewRequest,
    ComparisonReviewResponse,
    IntentImpactAssessment,
    IntentRevision,
    RebuildDirective,
    TargetDecision,
    TargetDecisionInput,
)
from campus_job_agent.schemas.matching_graph import (
    MatchingBudget,
    MatchingCounter,
    ProfileMatchingGraphState,
)
from campus_job_agent.schemas.llm import (
    LLMCallRecord,
    LLMConfig,
    LLMRequest,
    LLMResponse,
)
from campus_job_agent.schemas.tool import ToolResult
from campus_job_agent.schemas.human_interaction import (
    HumanAnswer,
    HumanInteractionRequest,
    HumanInteractionResponse,
    RequestedMaterial,
)
from campus_job_agent.schemas.role import (
    FamilyRequirementAggregate,
    HiringSignal,
    JobInstanceRoleProfile,
    Qualification,
    RoleFamilyProfile,
    RoleProfile,
    RoleRequirement,
)
from campus_job_agent.schemas.role_graph import (
    RoleCoverageAssessment,
    RoleCoverageGap,
    RoleProfileGraphState,
    RoleSearchBudget,
    RoleSearchCounter,
)
from campus_job_agent.schemas.source import (
    CredentialRef,
    ExperienceEvidenceRecord,
    FieldResolution,
    JobIdentityLink,
    JobPostingCluster,
    NormalizedJobPosting,
    OfficialSiteAdapterSpec,
    OfficialVerificationPlan,
    RoleQueryPlan,
    SearchScope,
    SourceBatch,
    SourceCapabilities,
    SourceDocument,
    SourceQuery,
    SourceRunReceipt,
)
from campus_job_agent.schemas.trace import (
    RuntimeErrorRecord,
    TraceEvent,
    VerificationResult,
)

__all__ = [
    "ParsedGoal",
    "SearchGoal",
    "PlanTask",
    "LLMConfig",
    "LLMRequest",
    "LLMResponse",
    "LLMCallRecord",
    "ToolResult",
    "TraceEvent",
    "VerificationResult",
    "RuntimeErrorRecord",
    "EvidenceArtifact",
    "EvidenceFragment",
    "EvidenceClaim",
    "ExtractedClaim",
    "ClaimExtractionBatch",
    "ClaimExtractor",
    "Provenance",
    "ProfileSnapshot",
    "CandidateProfile",
    "CapabilityAssessment",
    "EducationRecord",
    "ExperienceRecord",
    "ResponsibilityBoundary",
    "EvidenceCoverage",
    "InformationGap",
    "SufficiencyAssessment",
    "QuestionItem",
    "QuestionPlan",
    "ProfileCorrection",
    "ProfileVersionDiff",
    "HumanAnswer",
    "RequestedMaterial",
    "HumanInteractionRequest",
    "HumanInteractionResponse",
    "CandidateProfileGraphState",
    "BudgetState",
    "CounterState",
    "DocumentExtraction",
    "ExtractionUnit",
    "CareerIntent",
    "IntentConstraint",
    "migrate_legacy_career_intent",
    "RoleProfile",
    "RoleRequirement",
    "HiringSignal",
    "Qualification",
    "FamilyRequirementAggregate",
    "JobInstanceRoleProfile",
    "RoleFamilyProfile",
    "SearchScope",
    "SourceCapabilities",
    "SourceQuery",
    "RoleQueryPlan",
    "SourceDocument",
    "SourceBatch",
    "SourceRunReceipt",
    "NormalizedJobPosting",
    "ExperienceEvidenceRecord",
    "JobPostingCluster",
    "OfficialVerificationPlan",
    "JobIdentityLink",
    "FieldResolution",
    "OfficialSiteAdapterSpec",
    "CredentialRef",
    "RoleCoverageGap",
    "RoleCoverageAssessment",
    "RoleSearchBudget",
    "RoleSearchCounter",
    "RoleProfileGraphState",
    "GapAssessment",
    "GapItem",
    "migrate_legacy_gap_assessment",
    "MatchingInputSet",
    "QualificationAssessment",
    "RequirementAssessment",
    "CoverageContribution",
    "CoverageBreakdown",
    "PreferenceAssessment",
    "ComparisonEntry",
    "ComparisonSet",
    "JobMatchExplanation",
    "MatchExplanation",
    "TargetDecisionInput",
    "TargetDecision",
    "IntentRevision",
    "IntentImpactAssessment",
    "RebuildDirective",
    "ComparisonReviewRequest",
    "ComparisonReviewResponse",
    "MatchingBudget",
    "MatchingCounter",
    "ProfileMatchingGraphState",
]
